### ISSUE TITLE
Protein fasta

### ISSUE THREAD

**Issue by eduardoping** [SysBioChalmers/Yeast-Species-GEMs#100]
Hello, 

I would like to know if you have the protein fasta files with the gene tags like the GPR in the models. The gene tags provided by Shen 2018 are not the same. 

Thanks,

**Comment by hongzhonglu** [comment]
Hi @eduardoping  you can find the ID mapping from 
 https://github.com/SysBioChalmers/Multi_scale_evolution/tree/main/pan_genome/result/id_mapping.

**Comment by eduardoping** [comment]
Hi, 

Got it. Thank you!
