### ISSUE TITLE
How to estimate the gene relation for new rxns found by different annotation method?

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/Yeast-Species-GEMs#72]
Here, in preparation of pan-GEM for 332 yeast species plus 11 fungal species, different gene function annotation methods are used, including EggNog web annotation, kegg web annotation, RAVEN2-biocyc method, RAVEN2-kegg method. As a result, for the same reaction, the gene association from different methods can be different and meanwhile the same gene can be connected with different rxns depend on the annotation method. Thus we need define a unified pipeline to get the reliable new GPRs for the pan-GEMs of yeast species. Now we have two potential procedures:
1) Put all information from different sources together.
2) If the rxns have the genes from EggNog and kegg, then only these gene were used. Otherwise the genes from RAVEN2 are used. (Note: do not change the rxns related to substrate usage as they are manully checked rxns).

I personally prefer to the second procedure.  Hi Ed and Feiran @edkerk @feiranl, how do think of this issue?

**Comment by feiranl** [comment]
I don't see we have a very solid reason to trust EggNog and KEGG first. By doing so, I am afraid we are making things more complex. Then why not use all the info together to simplify the pipeline.

**Comment by edkerk** [comment]
I also do not see a strong argument for prioritizing EggNog and KEGG, the only one I would be careful with is RAVEN2-biocyc (this is just based on blastp to one representative protein sequence per reaction, much less sophisticated than RAVEN2-kegg's HMM-based search). So maybe only keep RAVEN2-biocyc as last-resort, and combine the other three approaches?

**Comment by hongzhonglu** [comment]
Thanks for all your nice comments! Then we can do it like:
**If the rxns have the genes from EggNog, kegg and RVAEN2_kegg, then only these gene were used. Otherwise the genes from RAVEN2-biocyc are used. (Note: do not change the rxns related to substrate usage as they are manully checked rxns).** 

I think this procedure is reasonable as EggNog, kegg and RVAEN2_kegg are relying on the KEGG database. Another issue is that for the same reaction, the corresponding gene from the three methods can be different. Do you have any suggestion about it?
