### ISSUE TITLE
The gene IDs in the draftGEM should be replaced by the specific IDs

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Yeast-Species-GEMs#74]
Right now, the gene IDs we are using in the final ssGEMs are the gene IDs ends with @seq, but in the draftGEMs built from RAVEN, the gene IDs are represented as a complex long IDs from its fasta file. This caused multiple round of ID mapping when adding the reaction and grRule from draftGEM. Therefore, we can genrate a new fasta file with specific gene IDs ends with @seq to generate new draftGEMs.

For example: gene ID is used as `Ambrosiozyma_monospora@Seq_6360` in the final GEMs, while the IDs such as` -processed-gene-0.15-mRNA-1_1&gene=augustus_masked-gi|1002318487|dbj|BCIP01000074.1|-processed-gene-0.15 CDS=1-321` exists in draftGEMs.

Issues:
Missing IDs in the IDmapping file.

<details><summary>List of missing IDs 
</summary>
-augustus-gene-2.16-mRNA-1_1&gene=maker-gi|1002318534|dbj|BCIP01000027.1|-augustus-gene-2.16&CDS=1-1005 Ambrosiozyma_monospora
-processed-gene-0.44-mRNA-1_1&gene=augustus_masked-gi|1002318560|dbj|BCIP01000001.1|-processed-gene-0.44&CDS=1-1311 Ambrosiozyma_monospora
-processed-gene-0.10-mRNA-1_1&gene=augustus_masked-gi|1002316705|dbj|BCKQ01000031.1|-processed-gene-0.10&CDS=1-2616 Ascoidea_asiatica
-processed-gene-5.42-mRNA-1_1&gene=augustus_masked-gi|1002316172|dbj|BCGC01000006.1|-processed-gene-5.42&CDS=1-1233 Candida_sorboxylosa
-processed-gene-1.78-mRNA-1_1&gene=augustus_masked-gi|1002316175|dbj|BCGC01000003.1|-processed-gene-1.78&CDS=1-3270 Candida_sorboxylosa
-augustus-gene-3.145-mRNA-1_1&gene=maker-gi|1002316176|dbj|BCGC01000002.1|-augustus-gene-3.145&CDS=1-1575 Candida_sorboxylosa
-processed-gene-6.103-mRNA-1_1&gene=augustus_masked-gi|1002316177|dbj|BCGC01000001.1|-processed-gene-6.103&CDS=1-1008 Candida_sorboxylosa
-processed-gene-3.119-mRNA-1_1&gene=augustus_masked-gi|1002316098|dbj|BCJV01000004.1|-processed-gene-3.119&CDS=1-1089 Candida_versatilis
-processed-gene-8.20-mRNA-1_1&gene=augustus_masked-gi|1002316348|dbj|BCGN01000005.1|-processed-gene-8.20&CDS=1-645 Sporopachydermia_quercuum
-processed-gene-17.124-mRNA-1_1&gene=augustus_masked-gi|1002316351|dbj|BCGN01000002.1|-processed-gene-17.124&CDS=1-2001 Sporopachydermia_quercuum

</details>

**Comment by hongzhonglu** [comment]
The missing IDs are due to that these sequences are not used to generate the gene clusters.

**Comment by hongzhonglu** [comment]
Now this issue is solved.
