### ISSUE TITLE
bug: in the draftGEMs file name

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Yeast-Species-GEMs#78]
Should use _  not the space in the filefolder. strain_specific_model_from_RAVEN_biocyc_55_110 not strain specific model from RAVEN biocyc_55_110

should use the same id for the species. there is a mistake in kegg draft model for Metschnikowia_matae_maris which is written as metschnikowia_matae_maris.

**Comment by hongzhonglu** [comment]
Now this is solved.
