### ISSUE TITLE
workflow to build the yeast-species-GEMs

### ISSUE THREAD

**Issue by lzhangUT** [SysBioChalmers/Yeast-Species-GEMs#98]
Hi, 
I am new to Yeast8 and Yeast species-GEMs, and I am interest and in a need of building new species GEM based on your workflow.
I read your paper and feel like I understand the workflow you had from the paper. however, when i look into the github, i am a liitle bit lost...
can you help clarify a workflow from the code perspective so I can reproduce your results? this may sound very naive, while for  beginners like me, i think it will be of great help. For example, you have one step in the paper stating "Reconstruction  of  pan-GEM  as  the  template  model  for  all  studiedspecies“. i am not sure which folder is more specific about this step and how are the folders in the github are connected. I would assume all the files needed to run and results generated are in the folder 'draft_GEM_all_yeast_species"', but I am not sure.
Do you have a workflow that can clarify that? it will be greatly appreciated and thank you very much for your work and contribution.

**Comment by hongzhonglu** [comment]
@lzhangUT Hi, sorry to miss this information. Now we have tried to refine the pipeline. But you can find the previous pipeline in https://github.com/SysBioChalmers/Yeast-Species-GEMs/blob/main/Reconstruction_script/Reconstruction/GetPanmodel.m. The key thing is that you should do a gene blast analysis to get the ortholog relation between the gene from your species and the pan-gene in the pan-model.

**Comment by lzhangUT** [comment]
Thanks for the information. It is useful and helpful.
